library(seewave)
audiomoth.rename("./Audiomoth_1_16-20juin", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Audiomoth_2_16-20juin", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Audiomoth_3_16-20juin", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Audiomoth_4_17-20juin", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Audiomoth_328_21-22mai", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Audiomoth_B_256_252_13-15mai", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Aurignac Audio 2020 AMTW 320 590", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Aurignac Audio 2020 AMTY 283 566", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Aurignac Audio 2020 AMTZ 323 539", overwrite = TRUE, tz = "", prefix = "")
audiomoth.rename("./Aurignac Audio 2020 AMTX 137 188", overwrite = TRUE, tz = "", prefix = "")
